name: fetch_vne

on:
  # Automatically trigger
  schedule:
  - cron: "0 */3 * * *"
  
  # Allow manually trigger
  workflow_dispatch:
  
env:
  MONGODB_DB: ${{ secrets.MONGODB_DB }}
  MONGODB_CONN_STR: ${{ secrets.MONGODB_CONN_STR }}

jobs:
  vne_thoi_su:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch VNE category 'Thoi su'
      run: |
        python main.py VNExpress https://vnexpress.net/thoi-su

  vne_the_gioi:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch VNE category 'The gioi'
      run: |
        python main.py VNExpress https://vnexpress.net/the-gioi

  vne_kinh_doanh:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch VNE category 'Kinh doanh'
      run: |
        python main.py VNExpress https://vnexpress.net/kinh-doanh

  vne_khoa_hoc:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch VNE category 'Khoa hoc'
      run: |
        python main.py VNExpress https://vnexpress.net/khoa-hoc

  vne_the_thao:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch VNE category 'The thao'
      run: |
        python main.py VNExpress https://vnexpress.net/the-thao

  vne_doi_song:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Fetch VNE category 'Doi song'
      run: |
        python main.py VNExpress https://vnexpress.net/doi-song
